# Site settings
title: Jeremias Menichelli
author: Jeremias Menichelli
description: "I work as a front end developer to make the web better, using JavaScript and CSS to build beautiful products, with a big eye on usability and performance."
url: jeremenichelli.github.io
baseurl: ""

# Build settings
port: 4000
exclude: [ "node_modules", "src", "gulpfile.babel.js", "README.md", "*.log", "*.json" ]

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Blog settings
permalink: /:year/:month/:title/
